#!/usr/bin/env bash
# Dependency drift report for pins Dependabot cannot track (see
# .github/dependabot.yml). Prints a Markdown report on stdout and exits 1
# when anything is outdated or unreadable, 0 when everything is current.
#
# Requires: bash, curl, jq, sort -V. Set GITHUB_TOKEN to avoid API rate limits.
set -uo pipefail

cd "$(dirname "$0")/../.."

drift=0
rows=""

npm_versions() {
  curl -fsSL "https://registry.npmjs.org/$1" | jq -r '.versions | keys[]' |
    grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V
}

# gh_versions REPO TAG_PREFIX — stable release versions, oldest first
gh_versions() {
  local auth=()
  [ -n "${GITHUB_TOKEN:-}" ] && auth=(-H "Authorization: Bearer $GITHUB_TOKEN")
  curl -fsSL "${auth[@]}" "https://api.github.com/repos/$1/releases?per_page=100" |
    jq -r '.[] | select(.prerelease | not) | .tag_name' |
    sed "s/^$2//" | grep -E '^[0-9]+(\.[0-9]+)+$' | sort -V
}

# add_row NAME SOURCE CURRENT LATEST_IN_MAJOR LATEST_OVERALL
add_row() {
  local name=$1 source=$2 current=$3 same_major=$4 latest=$5 status
  if [ -z "$current" ] || [ -z "$latest" ]; then
    status="⚠️ could not determine"
    drift=1
  elif [ "$current" != "$same_major" ]; then
    status="⬆️ update available"
    drift=1
  elif [ "$current" != "$latest" ]; then
    status="🔺 new major available"
    drift=1
  else
    status="✅ current"
  fi
  rows+="| $name | \`$source\` | ${current:-?} | ${same_major:-?} | ${latest:-?} | $status |"$'\n'
}

# check_versions NAME SOURCE CURRENT VERSIONS (newline-separated, sorted)
check_versions() {
  local latest same_major=""
  latest=$(tail -n1 <<<"$4")
  [ -n "$3" ] && same_major=$(grep -E "^${3%%.*}\." <<<"$4" | tail -n1)
  add_row "$1" "$2" "$3" "$same_major" "$latest"
}

config_version() {
  awk -v block="config :$1," '$0 == block {f=1} f && /version:/ {
    if (match($0, /"[^"]+"/)) print substr($0, RSTART + 1, RLENGTH - 2); exit
  }' config/config.exs
}

check_versions "esbuild" "config/config.exs" "$(config_version esbuild)" "$(npm_versions esbuild)"
check_versions "Tailwind CLI" "config/config.exs" "$(config_version tailwind)" "$(npm_versions tailwindcss)"

daisyui=$(grep -oP 'version = "\K[0-9.]+' assets/vendor/daisyui.js | head -n1)
check_versions "daisyUI" "assets/vendor/daisyui.js" "$daisyui" "$(npm_versions daisyui)"

# daisyui-theme.js carries no version string; it must be the exact file
# published with the vendored daisyui.js release.
theme_status="✅ matches daisyUI v${daisyui} release"
if [ -z "$daisyui" ]; then
  theme_status="⚠️ could not determine"
  drift=1
elif ! curl -fsSL "https://github.com/saadeghi/daisyui/releases/download/v${daisyui}/daisyui-theme.js" |
  cmp -s - assets/vendor/daisyui-theme.js; then
  theme_status="⚠️ differs from daisyUI v${daisyui} release"
  drift=1
fi
rows+="| daisyUI theme | \`assets/vendor/daisyui-theme.js\` | ${daisyui:-?} | — | — | $theme_status |"$'\n'

check_versions "topbar" "assets/vendor/topbar.js" \
  "$(grep -oP 'topbar \K[0-9.]+' assets/vendor/topbar.js | head -n1)" "$(npm_versions topbar)"
check_versions "Cropper.js" "assets/vendor/cropperjs/cropper.esm.js" \
  "$(grep -oP 'Cropper\.js v\K[0-9.]+' assets/vendor/cropperjs/cropper.esm.js | head -n1)" \
  "$(npm_versions cropperjs)"

check_versions "Elixir" ".tool-versions" \
  "$(awk '$1 == "elixir" {print $2}' .tool-versions)" "$(gh_versions elixir-lang/elixir v)"
check_versions "Erlang/OTP" ".tool-versions" \
  "$(awk '$1 == "erlang" {print $2}' .tool-versions)" "$(gh_versions erlang/otp OTP-)"

# CI image (ci/image/Dockerfile): tools with a version ARG and a checksum.
dockerfile_arg() { sed -nE "s/^ARG $1=(.*)$/\1/p" ci/image/Dockerfile; }

# Stable Rust releases come from the channel manifest, not GitHub releases.
rust_stable=$(curl -fsSL https://static.rust-lang.org/dist/channel-rust-stable.toml |
  sed -nE '/^\[pkg\.rust\]/,/^\[/ s/^version = "([0-9]+\.[0-9]+\.[0-9]+).*/\1/p' | head -n1)
check_versions "Rust toolchain (CI image)" "ci/image/Dockerfile" "$(dockerfile_arg RUST_TOOLCHAIN)" "$rust_stable"
check_versions "rustup (CI image)" "ci/image/Dockerfile" "$(dockerfile_arg RUSTUP_VERSION)" \
  "$(curl -fsSL https://static.rust-lang.org/rustup/release-stable.toml | sed -nE "s/^version = '([0-9.]+)'/\1/p")"
check_versions "GeckoDriver (CI image)" "ci/image/Dockerfile" "$(dockerfile_arg GECKODRIVER_VERSION)" \
  "$(gh_versions mozilla/geckodriver v)"
check_versions "Selenium Server (CI image)" "ci/image/Dockerfile" "$(dockerfile_arg SELENIUM_VERSION)" \
  "$(gh_versions SeleniumHQ/selenium selenium-)"

cat <<EOF
Weekly check of dependency pins that Dependabot cannot track
(generated by \`.github/workflows/dependency-drift.yml\`).

| Dependency | Pinned in | Current | Latest (same major) | Latest | Status |
|---|---|---|---|---|---|
$rows
Vendored assets are updated by replacing the file in \`assets/vendor/\`;
esbuild/Tailwind by bumping \`version:\` in \`config/config.exs\`; CI image
tools by bumping the version and SHA-256 in \`ci/image/Dockerfile\` (see
\`ci/image/README.md\`). Major
upgrades (🔺) need a migration review, not a drop-in swap.
EOF

exit "$drift"
