defmodule Baudrate.Auth.InviteCode do
  @moduledoc """
  Schema for invite codes used in invite-only registration mode.

  Each code is generated by an admin and can be used a limited number
  of times (default 1) to register new users. Codes can be revoked
  and have optional expiration dates.
  """

  use Ecto.Schema
  import Ecto.Changeset

  alias Baudrate.Setup.User

  schema "invite_codes" do
    field :code, :string
    field :used_at, :utc_datetime
    field :expires_at, :utc_datetime
    field :max_uses, :integer, default: 1
    field :use_count, :integer, default: 0
    field :revoked, :boolean, default: false

    belongs_to :created_by, User
    belongs_to :used_by, User

    timestamps()
  end

  @doc "Changeset for creating a new invite code."
  def changeset(invite_code, attrs) do
    invite_code
    |> cast(attrs, [:code, :created_by_id, :expires_at, :max_uses])
    |> validate_required([:code, :created_by_id])
    |> unique_constraint(:code)
  end

  @doc "Changeset for recording an invite code use (sets `used_by_id`, `used_at`, `use_count`)."
  def use_changeset(invite_code, attrs) do
    invite_code
    |> cast(attrs, [:used_by_id, :used_at, :use_count])
  end

  @doc "Changeset for revoking an invite code."
  def revoke_changeset(invite_code) do
    invite_code
    |> change(revoked: true)
  end
end
