defmodule BaudrateWeb.TotpSetupLive do
  @moduledoc """
  LiveView for first-time TOTP enrollment.

  Shown when `login_next_step/1` returns `:totp_setup` (admin/moderator
  without TOTP). The TOTP secret is generated by `SessionController.create/2`
  and stored in the cookie session as `:totp_setup_secret`.

  On mount, this LiveView reads the secret from the session, generates a QR
  code via `Auth.totp_qr_data_uri/1`, and displays it alongside the Base32-encoded
  secret for manual entry. The user scans the QR code with an authenticator app,
  enters the 6-digit code, and the form POSTs to `SessionController.totp_enable/2`
  which encrypts and persists the secret.
  """

  use BaudrateWeb, :live_view

  alias Baudrate.Auth

  @impl true
  def mount(_params, session, socket) do
    secret = session["totp_setup_secret"]

    if is_nil(secret) do
      {:ok, redirect(socket, to: "/login")}
    else
      username = socket.assigns.current_user.username
      uri = Auth.totp_uri(secret, username)
      qr_svg = Auth.totp_qr_data_uri(uri)
      secret_b32 = Base.encode32(secret, padding: false)
      policy = Auth.totp_policy(socket.assigns.current_user.role.name)

      socket =
        socket
        |> assign(:secret_b32, secret_b32)
        |> assign(:qr_svg, qr_svg)
        |> assign(:policy, policy)
        |> assign(:form, to_form(%{"code" => ""}, as: :totp))
        |> assign(:trigger_action, false)
        |> assign(:page_title, gettext("TOTP Setup"))

      {:ok, socket}
    end
  end

  @impl true
  def handle_event("validate", %{"totp" => params}, socket) do
    {:noreply, assign(socket, :form, to_form(params, as: :totp))}
  end

  @impl true
  def handle_event("submit", %{"totp" => %{"code" => code}}, socket) do
    code = String.trim(code)

    if String.match?(code, ~r/^\d{6}$/) do
      socket =
        socket
        |> assign(:code, code)
        |> assign(:trigger_action, true)

      {:noreply, socket}
    else
      socket =
        socket
        |> put_flash(:error, gettext("Please enter a 6-digit code."))
        |> assign(:form, to_form(%{"code" => ""}, as: :totp))

      {:noreply, socket}
    end
  end
end
