defmodule BaudrateWeb.Endpoint do
  @moduledoc """
  Phoenix endpoint — the entry point for all HTTP requests.

  ## Session Configuration

  Sessions are stored in signed + encrypted cookies with the following settings:

    * `store: :cookie` — no server-side session store needed (session data is
      minimal: tokens and flags)
    * `same_site: "Lax"` — CSRF protection for cross-origin requests
    * `max_age: 14 days` — cookie expiry matching the server-side session TTL
    * Signing and encryption salts are configured separately for defense in depth

  The `secure` flag is not set here because `force_ssl` in `config/prod.exs`
  configures `Plug.SSL` which sets `secure: true` on all cookies in production.
  In dev/test, cookies must work over plain HTTP (localhost), so omitting
  `secure` globally is correct.

  The LiveView socket also receives session data via `connect_info`, enabling
  `on_mount` hooks to access session tokens.
  """

  use Phoenix.Endpoint, otp_app: :baudrate

  # The session will be stored in the cookie and both signed and encrypted.
  @session_options [
    store: :cookie,
    key: "_baudrate_key",
    signing_salt: "mse//7wp",
    encryption_salt: "rK3nP+Qb",
    same_site: "Lax",
    max_age: 14 * 86_400
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:peer_data, session: @session_options]],
    longpoll: [connect_info: [:peer_data, session: @session_options]]

  # Extract real client IP from proxy header (configured in prod.exs only).
  # Must run before any rate-limiting plug so buckets use the real client IP.
  plug BaudrateWeb.Plugs.RealIp

  # Set Content-Disposition: attachment for non-image uploads to prevent
  # inline rendering of PDFs/ZIPs that could execute JS in site origin.
  # Must run before Plug.Static so headers are registered via before_send.
  plug BaudrateWeb.Plugs.AttachmentHeaders

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :baudrate,
    gzip: not code_reloading?,
    only: BaudrateWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :baudrate
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug BaudrateWeb.Router
end
