defmodule BaudrateWeb.Endpoint do
  @moduledoc """
  Phoenix endpoint — the entry point for all HTTP requests.

  ## Session Configuration

  Sessions are stored in signed + encrypted cookies with the following settings:

    * `store: :cookie` — no server-side session store needed (session data is
      minimal: tokens and flags)
    * `same_site: "Lax"` — CSRF protection for cross-origin requests
    * `max_age: 14 days` — cookie expiry matching the server-side session TTL
    * Signing and encryption salts are configured separately for defense in depth

    * `secure: true` in production — set explicitly, not inherited

  The moduledoc used to claim `Plug.SSL` sets `secure: true` on all cookies.
  It does not: it adds HSTS and redirects http→https. What actually set the
  flag was `Plug.Conn.put_resp_cookie/4` looking at `conn.scheme`, which
  depends entirely on `rewrite_on: [:x_forwarded_proto]` and therefore on the
  proxy sending that header. The shipped nginx template does send it, so the
  flag was present in the supported deployment — but an operator fronting the
  app with a terminator that omits the header got a session cookie with no
  `Secure` attribute, silently, with a green test suite. Set it here so it
  does not depend on a header. Dev and test stay without it, because cookies
  must work over plain HTTP on localhost.

  The LiveView socket also receives session data via `connect_info`, enabling
  `on_mount` hooks to access session tokens.
  """

  use Phoenix.Endpoint, otp_app: :baudrate

  # The session will be stored in the cookie and both signed and encrypted.
  @session_options [
    store: :cookie,
    key: "_baudrate_key",
    signing_salt: "mse//7wp",
    encryption_salt: "rK3nP+Qb",
    same_site: "Lax",
    max_age: 14 * 86_400,
    secure: Mix.env() == :prod
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [
      connect_info: [:peer_data, :x_headers, :user_agent, :uri, session: @session_options]
    ],
    longpoll: [
      connect_info: [:peer_data, :x_headers, :user_agent, :uri, session: @session_options]
    ]

  # Allow browser tests (Wallaby) to share the Ecto sandbox connection
  if Application.compile_env(:baudrate, :sql_sandbox) do
    plug Phoenix.Ecto.SQL.Sandbox
  end

  # Extract real client IP from proxy header (configured in prod.exs only).
  # Must run before any rate-limiting plug so buckets use the real client IP.
  plug BaudrateWeb.Plugs.RealIp

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :baudrate,
    gzip: not code_reloading?,
    only: BaudrateWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :baudrate
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    body_reader: {BaudrateWeb.Plugs.CacheBodyReader, :read_body, []},
    json_decoder: Phoenix.json_library(),
    length: 1_000_000

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug BaudrateWeb.Router
end
