defmodule Baudrate.Content.Markdown do
  @moduledoc """
  Converts Markdown text to sanitized HTML using Earmark.

  After Earmark renders Markdown to HTML, a post-processing step strips
  any HTML tags not in a known-safe set (those generated by Earmark itself).
  This prevents injection of `<script>`, `<iframe>`, or other unsafe elements
  that users could include as raw HTML in their Markdown source.
  """

  @safe_tags MapSet.new(~w[
    p br hr
    h1 h2 h3 h4 h5 h6
    em strong del
    a code pre blockquote
    ul ol li
    table thead tbody tr th td
    img
  ])

  @doc """
  Renders a Markdown string to sanitized HTML.

  Returns an empty string for `nil` or blank input.

  ## Examples

      iex> Baudrate.Content.Markdown.to_html("**bold**")
      "<p>\n<strong>bold</strong></p>\n"

      iex> Baudrate.Content.Markdown.to_html(nil)
      ""
  """
  @spec to_html(String.t() | nil) :: String.t()
  def to_html(nil), do: ""
  def to_html(""), do: ""

  def to_html(text) when is_binary(text) do
    text
    |> Earmark.as_html!()
    |> sanitize_html()
  end

  defp sanitize_html(html) do
    Regex.replace(~r/<(\/?)([a-zA-Z][a-zA-Z0-9]*)((?:\s[^>]*)?)>/u, html, fn
      _match, slash, tag, attrs ->
        lower = String.downcase(tag)

        if MapSet.member?(@safe_tags, lower) do
          safe_attrs = sanitize_attrs(lower, attrs)
          "<#{slash}#{lower}#{safe_attrs}>"
        else
          escaped_attrs = escape_entities(attrs)
          "&lt;#{slash}#{tag}#{escaped_attrs}&gt;"
        end
    end)
  end

  defp sanitize_attrs("a", attrs) do
    case Regex.run(~r/href="([^"]*)"/, attrs) do
      [_, href] ->
        uri = URI.parse(href)

        if uri.scheme in [nil, "http", "https", "mailto"] do
          safe_href = escape_entities(href)
          ~s( href="#{safe_href}" rel="nofollow noopener")
        else
          ""
        end

      _ ->
        ""
    end
  end

  defp sanitize_attrs("code", attrs) do
    case Regex.run(~r/class="language-([a-zA-Z0-9_+-]+)"/, attrs) do
      [_, lang] -> ~s( class="language-#{lang}")
      _ -> ""
    end
  end

  defp sanitize_attrs("img", attrs) do
    src =
      case Regex.run(~r/src="([^"]*)"/, attrs) do
        [_, s] ->
          uri = URI.parse(s)
          if uri.scheme in [nil, "http", "https"], do: ~s( src="#{escape_entities(s)}"), else: ""

        _ ->
          ""
      end

    alt =
      case Regex.run(~r/alt="([^"]*)"/, attrs) do
        [_, a] -> ~s( alt="#{escape_entities(a)}")
        _ -> ""
      end

    src <> alt
  end

  defp sanitize_attrs(_tag, _attrs), do: ""

  defp escape_entities(text) do
    text
    |> String.replace("&", "&amp;")
    |> String.replace("<", "&lt;")
    |> String.replace(">", "&gt;")
    |> String.replace("\"", "&quot;")
  end
end
