import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :baudrate, BaudrateWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :baudrate, BaudrateWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    hsts: true,
    subdomains: true,
    preload: true,
    expires: 63_072_000
  ]

# Extract real client IP from X-Forwarded-For header set by the reverse proxy.
# Your reverse proxy MUST set (not append to) this header for security.
# Without this, all requests share the proxy's IP for rate limiting.
#
# `trusted_proxies` is an allow-list of immediate peer addresses (exact IPs or
# CIDR ranges). The header is honored only when the connection arrives from a
# listed peer; direct connections from other addresses cannot spoof the IP.
# Override via runtime.exs (e.g. BAUDRATE_TRUSTED_PROXIES) when the proxy
# does not run on the same host.
config :baudrate, BaudrateWeb.Plugs.RealIp,
  header: "x-forwarded-for",
  trusted_proxies: ["127.0.0.1", "::1"]

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
