---
- name: Reload systemd
  become_user: root
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart baudrate
  become_user: root
  ansible.builtin.systemd:
    name: baudrate
    state: restarted
